FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npx nest build && npx nest build products

EXPOSE 3001

CMD ["node", "dist/apps/products/products/src/main.js"]
